### ISSUE TITLE
Download and install desktop firefox on first-run of FxR Desktop

### ISSUE THREAD

**Issue by patrickoshaughnessey** [MozillaReality/FirefoxRealityPC#192]
We will only ship the Unity parts in the Viveport package, and on first-run, have it download and install Firefox (into C:\Program Files). Firefox will then update on it’s own on the normal release update cycle. If we update the Unity-only parts, users will get a notification via an in-app notification.

**Comment by TomasEkeli** [comment]
Please don't hard-code in the location to "C:\Program Files", it's a sane default but users may want it somewhere else.
